core/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('notes.urls')),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

notes/urls.py
from django.conf.urls import url

from . import views

app_name = 'notes'

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^add$', views.add, name='add'),
    url(r'^edit/(?P<note_ref>[0-9a-z-]+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<note_ref>[0-9a-z-]+)/$', views.delete, name='delete'),
    url(r'^view/(?P<note_ref>[0-9a-z-]+)/$', views.view, name='view')
]

notes/models.py
import uuid
from django.db import models
from django.urls import reverse

# Create your models here.
class Note(models.Model):
    title = models.CharField(max_length=200, default='')
    text = models.TextField()
    time = models.DateField(auto_now=True)
    passwd = models.CharField(max_length=30, default='')
    ref = models.UUIDField(editable=False, default=uuid.uuid4)

    def __str__(self):
        return self.title

    def link(self, type='view'):
        name = 'notes:%s' % type
        return reverse(name, args=(str(self.ref), ))

notes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse


from .models import Note

# Create your views here.
def list(request):

    return render(request, 'list.html', {
        'notes': Note.objects.order_by('-id'),
    })


def add(request):

    if request.method == 'POST':

        text = request.POST['text']
        title = text.split('\n')[0].strip('# ')
        passwd = request.POST['passwd']
        note = Note(title=title, text=text, passwd=passwd)

        note.save()

        if len(passwd):
            request.session[str(note.ref)] = True

        return HttpResponseRedirect(reverse('notes:view', args=(note.ref, )))
    else:
        return render(request, 'add.html')

def edit(request, note_ref):

    note = get_object_or_404(Note, ref=note_ref)

    if request.method == 'POST':
        text = request.POST['text']
        title = text.split('\n')[0].strip('# ')
        passwd = request.POST['passwd']

        note.text = text
        note.title = title
        note.passwd = passwd

        if len(passwd):
            request.session[note_ref] = True

        note.save()

        return HttpResponseRedirect(reverse('notes:view', args=(note.ref, )))

    return render(request, 'edit.html', {
        'note': note
    })


def delete(request, note_ref):

    note = get_object_or_404(Note, ref=note_ref)

    note.delete()

    return HttpResponseRedirect(reverse('notes:list'))


def view(request, note_ref):

    note = get_object_or_404(Note, ref=note_ref)

    note_passwd_len = len(note.passwd)

    if request.method == 'POST' and note.passwd == request.POST['passwd']:

        request.session[note_ref] = True


    if note_passwd_len == 0 or note_ref in request.session:

        return render(request, 'view.html', {
            'note': note
        })

    return HttpResponse(render(request, 'passwd.html'), status=401)

notes/templates/add.html
<!DOCTYPE html>
<html>
<head>
    <title>Markdown Editor</title>
    {% load static %}
    <link href="{% static "favicon.ico" %}" rel="shortcut icon"/>
    <script src="{% static "markdown-it.js" %}"></script>
    <script src="{% static "markdown-it-footnote.js" %}"></script>
    <script src="{% static "highlight.pack.js" %}"></script>
    <script src="{% static "emojify.js" %}"></script>
    <script src="{% static "codemirror/lib/codemirror.js" %}"></script>
    <script src="{% static "codemirror/overlay.js" %}"></script>
    <script src="{% static "codemirror/xml/xml.js" %}"></script>
    <script src="{% static "codemirror/markdown/markdown.js" %}"></script>
    <script src="{% static "codemirror/gfm/gfm.js" %}"></script>
    <script src="{% static "codemirror/javascript/javascript.js" %}"></script>
    <script src="{% static "codemirror/css/css.js" %}"></script>
    <script src="{% static "codemirror/htmlmixed/htmlmixed.js" %}"></script>
    <script src="{% static "codemirror/lib/util/continuelist.js" %}"></script>
    <script src="{% static "rawinflate.js" %}"></script>
    <script src="{% static "rawdeflate.js" %}"></script>
    <link rel="stylesheet" href="{% static "base16-light.css" %}">
    <link rel="stylesheet" href="{% static "codemirror/lib/codemirror.css" %}">
    <link rel="stylesheet" href="{% static "default.css" %}">
    <style type="text/css">
        body {
            margin: 0;
        }

        .CodeMirror pre {
            line-height: 16px;
        }

        #in {
            position: fixed;
            top: 0;
            left: 0;
            bottom: 0;
            width: 50%;
            height: auto;
            overflow: auto;
            font-size: 12px;
            box-shadow: -10px 2px 6px 10px rgba(0, 0, 0, 0.4);
        }

        #in #toolbar {
            position: fixed;
            bottom: 0;
            right: 50%;
            width: auto;
            height: 40px;
            overflow: auto;
            font-size: 12px;
            z-index: 10;
            box-shadow: -1px 2px 6px 1px rgba(0, 0, 0, 0.4);
            padding: 10px;
            text-align: right;
        }

        #in #toolbar button {
            background-color: #0d71bb;
            color: #fff;
            text-shadow: none;
            box-shadow: 0 0 0 0 rgba(34,36,38,.15) inset;
            font-size: 14px;
            cursor: pointer;
            display: inline-block;
            border: none;
            vertical-align: middle;
            font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
            padding: 10px 16px;
            text-transform: none;
            font-weight: 700;
            font-style: normal;
            text-align: center;
            border-radius: 4px;
        }

       #in #toolbar input {
            font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
            vertical-align: middle;
            width: 150px;
            height: 30px;
            padding: 2px 10px;
            font-size: 14px;
            background: #FFF;
            border: 1px solid rgba(34,36,38,.15);
            color: rgba(0,0,0,.87);
            border-radius: 4px;
        }

        .CodeMirror {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            width: auto;
            height: auto;
        }

        .CodeMirror-scroll {
            padding: 30px;
            box-sizing: border-box;
        }

        #out {
            position: fixed;
            top: 0;
            right: 0;
            left: 50%;
            bottom: 0;
            overflow: auto;
            padding: 10px;
            padding-left: 20px;
            color: #444;
            font-family: Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif;
            font-size: 16px;
            line-height: 1.5em
        }

        .emoji {
            width: 1em;
            height: 1em;
            vertical-align: baseline;
        }

        @media screen and (max-width: 1024px) {
            #in {
                display: none;
            }

            #out {
                left: 0;
                padding-left: 10px;
            }
        }

        .cm-header-1 {
            font-size: 2em;
        }

        .cm-header-2 {
            font-size: 1.75em;
        }

        .cm-header-3 {
            font-size: 1.5em;
        }

        .cm-header-4 {
            font-size: 1.3em;
        }

        .cm-header-5 {
            font-size: 1.2em;
        }

        .cm-header-6 {
            font-size: 1.15em;
        }

        .cm-quote {
            color: #90a959;
            font-style: italic;
        }

        .view #in {
            display: none;
        }

        .view #out {
            left: 0;
            padding-left: 10px;
        }

        a {
            color: #0645ad;
            text-decoration: none;
        }

        a:visited {
            color: #0b0080;
        }

        a:hover {
            color: #06e;
        }

        a:active {
            color: #faa700;
        }

        a:focus {
            outline: thin dotted;
        }

        a:hover, a:active {
            outline: 0;
        }

        p {
            margin: 1em 0;
        }

        img {
            max-width: 100%;
        }

        h1, h2, h3, h4, h5, h6 {
            font-weight: normal;
            color: #111;
            line-height: 1em;
        }

        h4, h5, h6 {
            font-weight: bold;
        }

        h1 {
            font-size: 2.5em;
        }

        h2 {
            font-size: 2em;
            border-bottom: 1px solid silver;
            padding-bottom: 5px;
        }

        h3 {
            font-size: 1.5em;
        }

        h4 {
            font-size: 1.2em;
        }

        h5 {
            font-size: 1em;
        }

        h6 {
            font-size: 0.9em;
        }

        blockquote {
            color: #666666;
            margin: 0;
            padding-left: 3em;
            border-left: 0.5em #EEE solid;
        }

        hr {
            display: block;
            height: 2px;
            border: 0;
            border-top: 1px solid #aaa;
            border-bottom: 1px solid #eee;
            margin: 1em 0;
            padding: 0;
        }

        pre, code {
            color: #000;
            font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
            font-size: 0.94em; /* 0.94 = 0.88 + (1.00 - 0.88) / 2 */
            border-radius: 3px;
            background-color: #F8F8F8;
            border: 1px solid #CCC;
        }

        pre {
            white-space: pre-wrap;
            word-wrap: break-word;
            padding: 5px;
        }

        pre code {
            border: 0 !important;
            background: transparent !important;
            line-height: 1.3em;
        }

        code {
            padding: 0 3px 0 3px;
        }

        sub, sup {
            font-size: 75%;
            line-height: 0;
            position: relative;
            vertical-align: baseline;
        }

        sup {
            top: -0.5em;
        }

        sub {
            bottom: -0.25em;
        }

        ul, ol {
            margin: 1em 0;
            padding: 0 0 0 2em;
        }

        li p:last-child {
            margin: 0;
        }

        dd {
            margin: 0 0 0 2em;
        }

        img {
            border: 0;
            -ms-interpolation-mode: bicubic;
            vertical-align: middle;
        }

        table {
            border-collapse: collapse;
            border-spacing: 0;
        }

        td, th {
            vertical-align: top;
            padding: 4px 10px;
            border: 1px solid #bbb;
        }

        tr:nth-child(even) td, tr:nth-child(even) th {
            background: #eee;
        }
    </style>
</head>
<body>
<div id="in">
    <div id="toolbar">
        <input type="password" form="add-form" placeholder="密码, 如有需要请填写" name="passwd" />
        <button type="submit" form="add-form"> Submit </button>
    </div>

    <form method="post" action="{% url 'notes:add' %}" id="add-form">
        {% csrf_token %}
        <textarea id="code" name="text"></textarea>
    </form>
</div>

<div id="out"></div>

<script type="text/javascript">
    var URL = window.URL || window.webkitURL || window.mozURL || window.msURL;
    navigator.saveBlob = navigator.saveBlob || navigator.msSaveBlob || navigator.mozSaveBlob || navigator.webkitSaveBlob;

    // Because highlight.js is a bit awkward at times
    var languageOverrides = {
        js: 'javascript',
        html: 'xml'
    };

    emojify.setConfig({img_dir: '{% static 'emoji' %}'});

    var md = markdownit({
        html: true,
        highlight: function (code, lang) {
            if (languageOverrides[lang]) lang = languageOverrides[lang];
            if (lang && hljs.getLanguage(lang)) {
                try {
                    return hljs.highlight(lang, code).value;
                } catch (e) {
                }
            }
            return '';
        }
    }).use(markdownitFootnote);


    function update(e) {
        setOutput(e.getValue());
    }

    function setOutput(val) {
        val = val.replace(/<equation>((.*?\n)*?.*?)<\/equation>/ig, function (a, b) {
            return '<img src="http://latex.codecogs.com/png.latex?' + encodeURIComponent(b) + '" />';
        });

        var out = document.getElementById('out');
        var old = out.cloneNode(true);
        out.innerHTML = md.render(val);
        emojify.run(out);

        var allold = old.getElementsByTagName("*");
        if (allold === undefined) return;

        var allnew = out.getElementsByTagName("*");
        if (allnew === undefined) return;

        for (var i = 0, max = Math.min(allold.length, allnew.length); i < max; i++) {
            if (!allold[i].isEqualNode(allnew[i])) {
                out.scrollTop = allnew[i].offsetTop;
                return;
            }
        }
    }

    var editor = CodeMirror.fromTextArea(document.getElementById('code'), {
        mode: 'gfm',
        lineNumbers: false,
        matchBrackets: true,
        lineWrapping: true,
        theme: 'base16-light',
        extraKeys: {"Enter": "newlineAndIndentContinueMarkdownList"}
    });

    editor.on('change', update);

    document.addEventListener('drop', function (e) {
        e.preventDefault();
        e.stopPropagation();

        var reader = new FileReader();
        reader.onload = function (e) {
            editor.setValue(e.target.result);
        };

        reader.readAsText(e.dataTransfer.files[0]);
    }, false);

    update(editor);
    editor.focus();
</script>
</body>
</html>

notes/templates/edit.html
<!DOCTYPE html>
<html>
<head>
    <title>Markdown Editor</title>
    {% load static %}
    <link href="{% static "favicon.ico" %}" rel="shortcut icon"/>
    <script src="{% static "markdown-it.js" %}"></script>
    <script src="{% static "markdown-it-footnote.js" %}"></script>
    <script src="{% static "highlight.pack.js" %}"></script>
    <script src="{% static "emojify.js" %}"></script>
    <script src="{% static "codemirror/lib/codemirror.js" %}"></script>
    <script src="{% static "codemirror/overlay.js" %}"></script>
    <script src="{% static "codemirror/xml/xml.js" %}"></script>
    <script src="{% static "codemirror/markdown/markdown.js" %}"></script>
    <script src="{% static "codemirror/gfm/gfm.js" %}"></script>
    <script src="{% static "codemirror/javascript/javascript.js" %}"></script>
    <script src="{% static "codemirror/css/css.js" %}"></script>
    <script src="{% static "codemirror/htmlmixed/htmlmixed.js" %}"></script>
    <script src="{% static "codemirror/lib/util/continuelist.js" %}"></script>
    <script src="{% static "rawinflate.js" %}"></script>
    <script src="{% static "rawdeflate.js" %}"></script>
    <link rel="stylesheet" href="{% static "base16-light.css" %}">
    <link rel="stylesheet" href="{% static "codemirror/lib/codemirror.css" %}">
    <link rel="stylesheet" href="{% static "default.css" %}">
    <style type="text/css">
        body {
            margin: 0;
        }

        #in {
            position: fixed;
            top: 0;
            left: 0;
            bottom: 0;
            width: 50%;
            height: auto;
            overflow: auto;
            font-size: 12px;
            box-shadow: -10px 2px 6px 10px rgba(0, 0, 0, 0.4);
        }

        #in #toolbar {
            position: fixed;
            bottom: 0;
            right: 50%;
            width: auto;
            height: 40px;
            overflow: auto;
            font-size: 12px;
            z-index: 10;
            box-shadow: -1px 2px 6px 1px rgba(0, 0, 0, 0.4);
            padding: 10px;
            text-align: right;
        }

        #in #toolbar button {
            background-color: #0d71bb;
            color: #fff;
            text-shadow: none;
            box-shadow: 0 0 0 0 rgba(34,36,38,.15) inset;
            font-size: 14px;
            cursor: pointer;
            display: inline-block;
            border: none;
            vertical-align: middle;
            font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
            padding: 10px 16px;
            text-transform: none;
            font-weight: 700;
            font-style: normal;
            text-align: center;
            border-radius: 4px;
        }

        #in #toolbar input {
            font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
            vertical-align: middle;
            width: 150px;
            height: 30px;
            padding: 2px 10px;
            font-size: 14px;
            background: #FFF;
            border: 1px solid rgba(34,36,38,.15);
            color: rgba(0,0,0,.87);
            border-radius: 4px;
        }

        .CodeMirror pre {
            line-height: 16px;
        }

        .CodeMirror {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            width: auto;
            height: auto;
        }

        .CodeMirror-scroll {
            padding: 30px;
            box-sizing: border-box;
        }

        #out {
            position: fixed;
            top: 0;
            right: 0;
            left: 50%;
            bottom: 0;
            overflow: auto;
            padding: 10px;
            padding-left: 20px;
            color: #444;
            font-family: Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif;
            font-size: 16px;
            line-height: 1.5em
        }

        .emoji {
            width: 1em;
            height: 1em;
            vertical-align: baseline;
        }

        .cm-header-1 {
            font-size: 2em;
        }

        .cm-header-2 {
            font-size: 1.75em;
        }

        .cm-header-3 {
            font-size: 1.5em;
        }

        .cm-header-4 {
            font-size: 1.3em;
        }

        .cm-header-5 {
            font-size: 1.2em;
        }

        .cm-header-6 {
            font-size: 1.15em;
        }

        .cm-quote {
            color: #90a959;
            font-style: italic;
        }

        .view #in {
            display: none;
        }

        .view #out {
            left: 0;
            padding-left: 10px;
        }

        a {
            color: #0645ad;
            text-decoration: none;
        }

        a:visited {
            color: #0b0080;
        }

        a:hover {
            color: #06e;
        }

        a:active {
            color: #faa700;
        }

        a:focus {
            outline: thin dotted;
        }

        a:hover, a:active {
            outline: 0;
        }

        p {
            margin: 1em 0;
        }

        img {
            max-width: 100%;
        }

        h1, h2, h3, h4, h5, h6 {
            font-weight: normal;
            color: #111;
            line-height: 1em;
        }

        h4, h5, h6 {
            font-weight: bold;
        }

        h1 {
            font-size: 2.5em;
        }

        h2 {
            font-size: 2em;
            border-bottom: 1px solid silver;
            padding-bottom: 5px;
        }

        h3 {
            font-size: 1.5em;
        }

        h4 {
            font-size: 1.2em;
        }

        h5 {
            font-size: 1em;
        }

        h6 {
            font-size: 0.9em;
        }

        blockquote {
            color: #666666;
            margin: 0;
            padding-left: 3em;
            border-left: 0.5em #EEE solid;
        }

        hr {
            display: block;
            height: 2px;
            border: 0;
            border-top: 1px solid #aaa;
            border-bottom: 1px solid #eee;
            margin: 1em 0;
            padding: 0;
        }

        pre, code {
            color: #000;
            font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
            font-size: 0.94em; /* 0.94 = 0.88 + (1.00 - 0.88) / 2 */
            border-radius: 3px;
            background-color: #F8F8F8;
            border: 1px solid #CCC;
        }

        pre {
            white-space: pre-wrap;
            word-wrap: break-word;
            padding: 5px;
        }

        pre code {
            border: 0 !important;
            background: transparent !important;
            line-height: 1.3em;
        }

        code {
            padding: 0 3px 0 3px;
        }

        sub, sup {
            font-size: 75%;
            line-height: 0;
            position: relative;
            vertical-align: baseline;
        }

        sup {
            top: -0.5em;
        }

        sub {
            bottom: -0.25em;
        }

        ul, ol {
            margin: 1em 0;
            padding: 0 0 0 2em;
        }

        li p:last-child {
            margin: 0;
        }

        dd {
            margin: 0 0 0 2em;
        }

        img {
            border: 0;
            -ms-interpolation-mode: bicubic;
            vertical-align: middle;
        }

        table {
            border-collapse: collapse;
            border-spacing: 0;
        }

        td, th {
            vertical-align: top;
            padding: 4px 10px;
            border: 1px solid #bbb;
        }

        tr:nth-child(even) td, tr:nth-child(even) th {
            background: #eee;
        }

        #op {
            position: fixed;
            top: 0;
            right: 0;
        }

        #op #delete{

        }
    </style>
</head>
<body>

<div id="in">

    <div id="toolbar">
        <input type="password" form="edit-form" placeholder="密码, 如有需要请填写" name="passwd" />
        <button type="submit" form="edit-form"> Submit </button>
    </div>


    <form id="edit-form" method="post">
        {% csrf_token %}
        <textarea id="code" name="text">{{ note.text }}</textarea>
    </form>
</div>

<div id="out"></div>

<script type="text/javascript">
    var URL = window.URL || window.webkitURL || window.mozURL || window.msURL;
    navigator.saveBlob = navigator.saveBlob || navigator.msSaveBlob || navigator.mozSaveBlob || navigator.webkitSaveBlob;

    // Because highlight.js is a bit awkward at times
    var languageOverrides = {
        js: 'javascript',
        html: 'xml'
    };

    emojify.setConfig({img_dir: '{% static 'emoji' %}'});

    var md = markdownit({
        html: true,
        highlight: function (code, lang) {
            if (languageOverrides[lang]) lang = languageOverrides[lang];
            if (lang && hljs.getLanguage(lang)) {
                try {
                    return hljs.highlight(lang, code).value;
                } catch (e) {
                }
            }
            return '';
        }
    }).use(markdownitFootnote);

    function update(e) {
        setOutput(e.getValue());
    }

    function setOutput(val) {
        val = val.replace(/<equation>((.*?\n)*?.*?)<\/equation>/ig, function (a, b) {
            return '<img src="http://latex.codecogs.com/png.latex?' + encodeURIComponent(b) + '" />';
        });

        var out = document.getElementById('out');
        var old = out.cloneNode(true);
        out.innerHTML = md.render(val);
        emojify.run(out);

        var allold = old.getElementsByTagName("*");
        if (allold === undefined) return;

        var allnew = out.getElementsByTagName("*");
        if (allnew === undefined) return;

        for (var i = 0, max = Math.min(allold.length, allnew.length); i < max; i++) {
            if (!allold[i].isEqualNode(allnew[i])) {
                out.scrollTop = allnew[i].offsetTop;
                return;
            }
        }
    }

    var editor = CodeMirror.fromTextArea(document.getElementById('code'), {
        mode: 'gfm',
        lineNumbers: false,
        matchBrackets: true,
        lineWrapping: true,
        theme: 'base16-light',
        extraKeys: {"Enter": "newlineAndIndentContinueMarkdownList"}
    });


    editor.on('change', update);


    document.addEventListener('drop', function (e) {
        e.preventDefault();
        e.stopPropagation();

        var reader = new FileReader();
        reader.onload = function (e) {
            editor.setValue(e.target.result);
        };

        reader.readAsText(e.dataTransfer.files[0]);
    }, false);

    update(editor);
    editor.focus();
</script>
</body>
</html>

notes/templates/list.html
<html>
<head>

    <title>Notes</title>

    <style type="text/css">
        a {
            color: #428bca;
            text-decoration: none;
        }

        a:hover, a:focus {
            color: #2a6496;
        }

        a:active, a:hover {
            outline: 0;
        }

        .title a {
            display: block;
        }

        .list-group {
            border-radius: 4px;
            box-shadow: 0 1px 2px rgba(0,0,0,.075);
            padding-left: 0;
            width: 60%;
            margin: 40px auto;
        }

        .list-group-item:first-child {
            border-top-right-radius: 4px;
            border-top-left-radius: 4px;
        }

        .title {
            cursor: pointer;
        }

        .list-group-item {
            position: relative;
            display: block;
            padding: 10px 20px;
            margin-bottom: -1px;
            background-color: #fff;
            border: 1px solid #ddd;
            font-size: 14px;
        }

        .list-group-item:hover {
            background-color: #efefef;

        }

        .time {
            float: right;
            font-size: 12px;
            vertical-align: middle;
        }

        body {
            margin: 20px 30px auto 30px;
        }

    </style>
</head>

<body>
    <ul class="list-group">
        {% load link %}
        {% for note in notes.all %}
            <li class="list-group-item title">
                <a href="{{ note|link }}">
                    {{ note }}

                    <span class="time">
                        {{ note.time|date:'Y/m/d' }}
                    </span>
                </a>
            </li>
        {% endfor %}
    </ul>

</body>

notes/templates/passwd.html
<!DOCTYPE html>
<html>
<head>
    <title>Markdown Editor</title>
    {% load static %}
    <link href="{% static "favicon.ico" %}" rel="shortcut icon"/>
    <style type="text/css">
        body {
            margin: 0;
            height: 100%;
            width: 100%;
        }

        #passwd-form {
            position: fixed;
            bottom: 0;
            top: 40%;
            left: 50%;
            margin-left: -130px;
            margin-top: -20px;
            width: 280px;
            height: 40px;
            overflow: auto;
            font-size: 14px;
            box-shadow: -1px 2px 6px 1px rgba(0, 0, 0, 0.4);
            padding: 10px;
            text-align: center;
        }

        #passwd-form button {
            background-color: #0d71bb;
            color: #fff;
            text-shadow: none;
            box-shadow: 0 0 0 0 rgba(34,36,38,.15) inset;
            font-size: 14px;
            cursor: pointer;
            display: inline-block;
            border: none;
            vertical-align: middle;
            font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
            padding: 10px 16px;
            text-transform: none;
            font-weight: 700;
            font-style: normal;
            text-align: center;
            border-radius: 4px;
        }

        #passwd-form input {
            font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
            vertical-align: middle;
            width: 150px;
            height: 30px;
            padding: 2px 10px;
            font-size: 14px;
            background: #FFF;
            border: 1px solid rgba(34,36,38,.15);
            color: rgba(0,0,0,.87);
            border-radius: 4px;
        }

    </style>
</head>
<body>

<form method="post" id="passwd-form">
    {% csrf_token %}
    <input type="password" placeholder="请填写密码" name="passwd" />
    <button type="submit"> Submit </button>
</form>
</body>
</html>